#pragma once
// Auto-generated by the editor.
// Scripts do NOT need REGISTER_SCRIPT at the end — it is injected here.

#include "abyss_shared.hpp"
#include "abyss_fx.hpp"
#include "abyss_fx_burst.cpp"
REGISTER_SCRIPT(AbyssFxBurst);

#include "abyss_bolt.cpp"
REGISTER_SCRIPT(AbyssBolt);

#include "abyss_boss.cpp"
REGISTER_SCRIPT(AbyssBoss);

#include "abyss_checkpoint.cpp"
REGISTER_SCRIPT(AbyssCheckpoint);

#include "abyss_crawler.cpp"
REGISTER_SCRIPT(AbyssCrawler);

#include "abyss_lantern.cpp"
REGISTER_SCRIPT(AbyssLantern);

#include "abyss_lift.cpp"
REGISTER_SCRIPT(AbyssLift);

#include "abyss_player.cpp"
REGISTER_SCRIPT(AbyssPlayer);

#include "abyss_pause_controller.cpp"
REGISTER_SCRIPT(AbyssPauseController);

#include "abyss_portal.cpp"
REGISTER_SCRIPT(AbyssPortal);

#include "abyss_seal.cpp"
REGISTER_SCRIPT(AbyssSeal);

#include "abyss_slash.cpp"
REGISTER_SCRIPT(AbyssSlash);

#include "abyss_spitter.cpp"
REGISTER_SCRIPT(AbyssSpitter);

#include "abyss_turret.cpp"
REGISTER_SCRIPT(AbyssTurret);


#include "abyss_menu_controller.cpp"
REGISTER_SCRIPT(AbyssMenuController);

#include "abyss_ability_gate.cpp"
REGISTER_SCRIPT(AbyssAbilityGate);

#include "abyss_ability_unlock.cpp"
REGISTER_SCRIPT(AbyssAbilityUnlock);

#include "tilemap_terrain_generator.cpp"
REGISTER_SCRIPT(TilemapTerrainGenerator);

#include "abyss_progression_manager.cpp"
REGISTER_SCRIPT(AbyssProgressionManager);

#include "abyss_room.cpp"
REGISTER_SCRIPT(AbyssRoom);

#include "abyss_encounter_controller.cpp"
REGISTER_SCRIPT(AbyssEncounterController);

#include "abyss_pickup.cpp"
REGISTER_SCRIPT(AbyssPickup);

#include "abyss_ambient_drift.cpp"
REGISTER_SCRIPT(AbyssAmbientDrift);

#include "abyss_shard.cpp"
REGISTER_SCRIPT(AbyssShard);

